table Vehicle
	lineageTag: 25a10716-547d-4f83-b6f0-9104ef6b5d68

	column Make
		dataType: string
		isHidden
		lineageTag: 02a142ee-b9b0-4a8a-aa61-08b4cd51c7f4
		summarizeBy: none
		sourceColumn: Make

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Marque
		dataType: string
		isHidden
		lineageTag: 48926416-9b4f-4758-b0c5-d67d8503d444
		summarizeBy: none
		sourceColumn: Marque

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VehicleType
		dataType: string
		isHidden
		lineageTag: db4896cb-a8f5-4f73-b675-79e03ffda972
		summarizeBy: none
		sourceColumn: VehicleType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VehicleKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a695b04c-c127-421d-8ffc-60c1222dfe13
		summarizeBy: none
		sourceColumn: VehicleKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Vehicle Hierarchy'
		lineageTag: 2f528c6e-6318-43e1-8734-494c2301dcce

		level Make
			lineageTag: 6b983d85-fefb-4618-a4ce-413013834cbc
			column: Make

		level Marque
			lineageTag: f2a5d37c-b8bf-4a2f-9cf5-e8cee4f6b4c3
			column: Marque

		level 'Vehicle Type'
			lineageTag: 39a4a8e3-9c35-4c7f-a089-c200fa69199a
			column: VehicleType

	partition Vehicle = m
		mode: import
		source =
				let
				    Source = Table.Combine({Sales2324, Sales25}),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Make", "Marque", "VehicleType"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "VehicleKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

