table Client
	lineageTag: 17575b18-95fe-4cf2-b972-2eab69c5521a

	column ClientID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 288adf30-ac96-4c9b-9b20-70b0c8a7e3ce
		summarizeBy: none
		sourceColumn: ClientID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Client Name'
		dataType: string
		lineageTag: 7cf38379-6974-4cc6-ab44-3e925d4794c7
		summarizeBy: none
		sourceColumn: Client Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Town
		dataType: string
		isHidden
		lineageTag: 694140ea-dd4c-4f45-b346-354a3e06b5f1
		dataCategory: City
		summarizeBy: none
		sourceColumn: Town

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: de015ec1-d5c2-4c30-8385-8a1ab99d7e81
		summarizeBy: none
		sourceColumn: CountryID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		isHidden
		lineageTag: 2f87c348-339c-435a-a345-17413418492d
		summarizeBy: none
		sourceColumn: ClientType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientSize
		dataType: string
		isHidden
		lineageTag: bc3cc9cc-bf8b-45f8-b58b-4613acdb2651
		summarizeBy: none
		sourceColumn: ClientSize

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsCreditWorthy
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0ab29d67-f340-43d8-8728-019fe2daf881
		summarizeBy: none
		sourceColumn: IsCreditWorthy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WebSite
		dataType: string
		isHidden
		lineageTag: 92b29067-cfb2-43ca-aae6-dc18a1ff87f0
		summarizeBy: none
		sourceColumn: WebSite

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		isHidden
		lineageTag: a718456c-b21f-40a1-b5b5-866eacaec641
		dataCategory: Country
		summarizeBy: none
		sourceColumn: CountryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Country Flag'
		dataType: string
		lineageTag: fccd6676-0746-4a99-ab81-3db08c3a5c88
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Country Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		isHidden
		lineageTag: f76abac6-a506-4c40-8a4c-eaeeaba46f6e
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: Continent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy Geography
		lineageTag: c2f67eb1-0ba4-479d-8bf0-c9fce49588cf

		level Continent
			lineageTag: 1350faa1-4aa6-4a99-82a6-1fae96b9de0c
			column: Continent

		level Country
			lineageTag: 7de146a6-63b0-460c-a2eb-591d2d194e98
			column: CountryName

		level City
			lineageTag: d182787e-2fbc-44ea-b3e0-e4fa34230fcd
			column: Town

		changedProperty = IsHidden

	hierarchy Type
		lineageTag: 2c2da37a-71c5-4040-8cad-ba2ea9bd80cf

		level 'Client Type'
			lineageTag: a352819b-205a-4528-a8ea-1af2880a7acc
			column: ClientType

		level 'Client Size'
			lineageTag: 27b2cbf6-a2ae-4f6f-b4bd-d698df6b48c0
			column: ClientSize

		changedProperty = IsHidden

	partition Client = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(OldClient, {"CountryID"}, Countries, {"CountryID"}, "Countries", JoinKind.LeftOuter),
				    #"Expanded Countries" = Table.ExpandTableColumn(Source, "Countries", {"CountryName", "CountryFlagURL"}, {"CountryName", "CountryFlagURL"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded Countries", {"CountryName"}, Continent, {"Country"}, "Continent", JoinKind.LeftOuter),
				    #"Expanded Continent" = Table.ExpandTableColumn(#"Merged Queries", "Continent", {"Continent"}, {"Continent"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Continent",{{"ClientName", "Client Name"}, {"CountryFlagURL", "Country Flag"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

