table Mileage
	lineageTag: bc0b56c3-fb20-4baa-b4dd-4a8f93a3cf7d

	column MileageRange
		dataType: string
		lineageTag: 14c74bce-0774-4eda-a744-fa880f63493d
		summarizeBy: none
		sourceColumn: MileageRange
		sortByColumn: MileageRangeSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MileageRangeSort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 15881eff-1329-4a19-8949-192b440771f7
		summarizeBy: none
		sourceColumn: MileageRangeSort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Mileage = m
		mode: import
		source =
				let
				    Source = Table.Combine({Sales2324, Sales25}),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"MileageRange", "MileageRangeSort"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

